#
## pithos main configuration
## =========================
#
# This file contains the following sections
#   - service
#   - logging
#   - options
#   - keystore
#   - bucketstore
#   - regions


## service configuration
## ---------------------
#
# indicates
service:
  host: '0.0.0.0'
  port: 8080


## logging configuration
## ---------------------
logging:
  level: info
  console: true
  files:
    - "/tmp/pithos.log"


## global options
## --------------
options:
  service-uri: 's3.gravitational.io'
  reporting: true
  server-side-encryption: true
  multipart-upload: true
  masterkey-provisioning: true
  masterkey-access: true
  default-region: 'G1'


## keystore configuration
## ----------------------
#
# Keystores associate an access key with
# an organization and secret key.
#
# They may offer provisioning capacities with the
# masterkey. The default provider relies on keys
# being defined inline.
keystore:
  keys:
    C28D2EE399E1A4CBC295D677:
      master: true
      tenant: 'ops@gravitational.io'
      secret: '4C22FFEA7A6C9F3AAFD223B30628F0EA1D50318C2F6F173F'
    CE9ED4F33A988422E7FA5DF1:
      tenant: 'pithos'
      secret: '1D8943238E6BC13E9030DF912FD047C4176C7758778E0E90'


## bucketstore configuration
## -------------------------
#
# The bucketstore is ring global and contains information
# on bucket location and global parameters.
#
# Its primary aim is to hold bucket location and ownership
# information.
#
# The default provider relies on cassandra.
bucketstore:
  default-region: 'G1'
  cluster: 'localhost'
  keyspace: 'storage'


## regions
## -------
#
# Regions are composed of a metastore and an arbitrary number
# of named storage classes which depend on a blobstore.
#
# The metastore holds metadata for the full region, as well as
# object storage-class placement information.
#
# The default implementation of both metastore and blobstore
# rely on cassandra.
#
regions:
  G1:
    metastore:
      cluster: 'localhost'
      keyspace: 'storage'
    storage-classes:
      standard:
        cluster: 'localhost'
        keyspace: 'storage'
        max-chunk: '128k'
        max-block-chunks: 1024
