apiVersion: v1
kind: Application
metadata:
  repository: gravitational.io
  name: pithos-app
  resourceVersion: 0.0.1
  namespace: default
base: gravitational.io/k8s-aws:0.0.0+latest
installer:
  provisioners:
    virsh:
      variables:
        devices:
          - device: vdc
            mb: 6144
  servers:
    node:
      min_count: 3
      cpu:
        min_count: 2
      ram:
        min_total_mb: 8000
      description: "pithos server"
      labels:
        role: node
        pithos-role: node
      directories:
        - name: /var/lib/gravity
          min_total_mb: 4000
      mounts:
        - source: /cassandra_data
          destination: /cassandra_data
          create_if_missing: true
hooks:
  install:
    spec:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: pithos-app-install
      spec:
        template:
          metadata:
            name: pithos-app-install
          spec:
            volumes:
              - name: temp
                emptyDir: {}
            restartPolicy: OnFailure
            containers:
              - name: bootstrap
                image: pithos-bootstrap:latest
                volumeMounts:
                  - name: temp
                    mountPath: /tmp
  uninstall:
    spec:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: pithos-app-uninstall
      spec:
        template:
          metadata:
            name: pithos-app-uninstall
          spec:
            restartPolicy: OnFailure
            containers:
              - name: bootstrap
                image: pithos-uninstall:latest
