apiVersion: v1
kind: Application
metadata:
  repository: gravitational.io
  name: pithos-app
  resourceVersion: 0.0.1
  namespace: default
base: gravitational.io/k8s-aws:0.0.0+latest
installer:
  provisioners:
    virsh:
      variables:
        devices:
          - device: vdc
            mb: 6144
  servers:
    node:
      cpu:
        min_count: 2
      ram:
        min_total_mb: 8000
      description: "pithos server"
      labels:
        role: "node"
        pithos-role: "node"
      directories:
        - name: /var/lib/gravity
          min_total_mb: 4000
      mounts:
        - source: /cassandra_data
          destination: /cassandra_data
          create_if_missing: true
      instance_types:
        aws_terraform:
          - m3.large
          - m3.xlarge
          - c3.large
          - c3.xlarge
          - c3.2xlarge
          - c3.4xlarge
          - i2.xlarge
          - i2.2xlarge
  flavors:
    title: "Select a flavor"
    items:
      - name: "single"
        description: "1 node"
        threshold:
          value: 1
          label: "1"
        profiles:
          node: 1
      - name: "triple"
        description: "3 nodes"
        threshold:
          value: 3
          label: "3"
        profiles:
          node: 3
hooks:
  install:
    spec:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: pithos-app-install
      spec:
        template:
          metadata:
            name: pithos-app-install
          spec:
            volumes:
              - name: temp
                emptyDir: {}
            restartPolicy: OnFailure
            containers:
              - name: bootstrap
                image: pithos-bootstrap:latest
                volumeMounts:
                  - name: temp
                    mountPath: /tmp
  uninstall:
    spec:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: pithos-app-uninstall
      spec:
        template:
          metadata:
            name: pithos-app-uninstall
          spec:
            restartPolicy: OnFailure
            containers:
              - name: bootstrap
                image: pithos-uninstall:latest
