apiVersion: v1
kind: Application
metadata:
  repository: gravitational.io
  name: pithos-app
  resourceVersion: 0.0.3
  namespace: default
base: gravitational.io/k8s-aws:1.3.0-3
installer:
  provisioners:
    virsh:
      variables:
        devices:
          - device: vdb
            mb: 10000
  servers:
    master:
      cpu:
        min_count: 1
      ram:
        min_total_mb: 4000
    node:
      cpu:
        min_count: 1
      min_count: 2
      description: "pithos server"
      labels:
        role: node
      ram:
        min_total_mb: 4000
      directories:
        - name: /var/lib/gravity
          min_total_mb: 4000
          fs_types: ["xfs", "btrfs"]
      mounts:
        - source: /cassandra_data
          destination: /cassandra_data
          create_if_missing: true
hooks:
  install:
    spec:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: pithos-app-install
      spec:
        template:
          metadata:
            name: pithos-app-install
          spec:
            restartPolicy: OnFailure
            containers:
              - name: bootstrap
                image: pithos-bootstrap:latest
  uninstall:
    spec:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: pithos-app-uninstall
      spec:
        template:
          metadata:
            name: pithos-app-uninstall
          spec:
            restartPolicy: OnFailure
            containers:
              - name: bootstrap
                image: pithos-uninstall:latest
