apiVersion: batch/v1
kind: Job
metadata:
  name: pithos-initialize
spec:
  template:
    metadata:
      name: pithos-initialize
    spec:
      restartPolicy: OnFailure
      containers:
      - image: pithos:latest
        name: pithos-initialize
        imagePullPolicy: Always
        command: ["/initialize.sh"]
        volumeMounts:
          - name: pithos-cfg
            mountPath: /etc/pithos
      volumes:
        - name: pithos-cfg
          configMap:
            name: pithos-cfg
