apiVersion: batch/v1
kind: Job
metadata:
  name: pithos-initialize
spec:
  template:
    metadata:
      name: pithos-initialize
    spec:
      restartPolicy: OnFailure
      containers:
        - image: cassandra:latest
          name: pithos-initialize
          command: ["/initialize.sh"]
