apiVersion: batch/v1
kind: Job
metadata:
  name: pithos-initialize
spec:
  template:
    metadata:
      name: pithos-initialize
    spec:
      restartPolicy: OnFailure
      containers:
        - image: cassandra:latest
          name: pithos-initialize
          command: ["/initialize.sh"]
          env:
            - name: CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cassandra-password
                  key: cassandra
          volumeMounts:
            - name: cassandra-ssl
              mountPath: /etc/ssl/cassandra
      volumes:
        - name: cassandra-ssl
          secret:
            secretName: cassandra-ssl
