apiVersion: v1
kind: Service
metadata:
  name: cassandra
  labels:
    app: pithos
spec:
  ports:
    - port: 9042
  selector:
    pithos: node
---
apiVersion: v1
kind: Service
metadata:
  name: pithos
  labels:
    app: pithos
spec:
  ports:
    - port: 8080
  selector:
    pithos: node
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: pithos
  labels:
    pithos: node
spec:
  template:
    metadata:
      labels:
        pithos: node
    spec:
      nodeSelector:
        pithos-role: node
      hostNetwork: true
      containers:
        - image: pithos:0.0.1
          name: pithos
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: pithos
          volumeMounts:
            - name: pithos-cfg
              mountPath: /etc/pithos
        - image: cassandra:0.0.1
          name: cassandra
          imagePullPolicy: Always
          env:
            - name: MAX_HEAP_SIZE
              value: 512M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
          volumeMounts:
            - name: data
              mountPath: /cassandra_data
            - name: cassandra-cfg
              mountPath: /etc/cassandra
      volumes:
        - name: data
          hostPath:
            path: /cassandra_data
        - name: cassandra-cfg
          configMap:
            name: cassandra-cfg
        - name: pithos-cfg
          configMap:
            name: pithos-cfg
