apiVersion: batch/v1
kind: Job
metadata:
  name: pithos-initialize
spec:
  template:
    metadata:
      name: pithos-initialize
    spec:
      restartPolicy: OnFailure
      hostNetwork: true
      containers:
        - image: cassandra:latest
          name: pithos-initialize
          command: ["/initialize.sh"]
          volumeMounts:
            - name: cassandra-ssl
              mountPath: /etc/ssl/cassandra
      volumes:
        - name: cassandra-ssl
          secret:
            secretName: cassandra-ssl
