apiVersion: v1
kind: Service
metadata:
  name: cassandra
  labels:
    app: pithos
spec:
  ports:
    - port: 9042
  selector:
    app: pithos
    pithos-role: cassandra
---
apiVersion: v1
kind: Service
metadata:
  name: pithos
  labels:
    app: pithos
spec:
  type: NodePort
  ports:
    - port: 443
      nodePort: 32002
      name: https
  selector:
    app: pithos
    pithos-role: proxy
---
apiVersion: v1
kind: Service
metadata:
  name: pithos-internal
  labels:
    app: pithos
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 32001
      name: http
  selector:
    app: pithos
    pithos-role: pithos
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: pithos-proxy
  labels:
    app: pithos
    pithos-role: proxy
spec:
  replicas: 1
  selector:
    app: pithos
    pithos-role: proxy
  template:
    metadata:
      labels:
        app: pithos
        pithos-role: proxy
    spec:
      containers:
      - image: pithos-proxy:latest
        name: proxy
        imagePullPolicy: Always
        ports:
          - containerPort: 80
            name: http
          - containerPort: 443
            name: https
        volumeMounts:
          - name: cluster-default-ssl
            mountPath: /etc/cluster-ssl
      volumes:
        - name: cluster-default-ssl
          secret:
            secretName: cluster-default-ssl
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: cassandra
  labels:
    app: pithos
    pithos-role: cassandra
spec:
  template:
    metadata:
      labels:
        app: pithos
        pithos-role: cassandra
    spec:
      nodeSelector:
        pithos-role: node
      hostNetwork: true
      containers:
        - image: cassandra:latest
          name: cassandra
          imagePullPolicy: Always
          env:
            - name: MAX_HEAP_SIZE
              value: 512M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
          volumeMounts:
            - name: data
              mountPath: /cassandra_data
            - name: cassandra-cfg
              mountPath: /etc/cassandra
      volumes:
        - name: data
          hostPath:
            path: /cassandra_data
        - name: cassandra-cfg
          configMap:
            name: cassandra-cfg
